server:
  port: 8054


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : candidate-service
          uri: lb://candidate-service
          predicates:
            - Path=/candidates/**
        - id: node-service
          uri: lb://node-service
          predicates:
            - Path=/api/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka